apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: argocd
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/emov00/homelab-deployment.git
        revision: main
        files:
        - path: homelab/infrastructure/argocd/config/config.yaml
  template:
    metadata:
      name: 'argocd'
    spec:
      project: "infrastructure"
      sources:
        - repoURL: ghcr.io/argoproj/argo-helm
          chart: argo-cd
          targetRevision: '{{.chartVersion}}'
          helm:
            valueFiles:
              - $values/homelab/infrastructure/argocd/values.yaml
        - repoURL: https://github.com/emov00/homelab-deployment.git
          targetRevision: main
          ref: values
      destination:
        name: homelab
        namespace: 'argocd'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
