apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: traefik
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - git:
        repoURL: https://github.com/emov00/homelab-deployment.git
        revision: main
        files:
          - path: homelab/infrastructure/traefik/config/config.yaml
  template:
    metadata:
      name: traefik
    spec:
      project: infrastructure
      sources:
        - repoURL: https://traefik.github.io/charts
          chart: traefik
          targetRevision: "{{.chartVersion}}"
          helm:
            valueFiles:
              - $values/homelab/infrastructure/traefik/values.yaml
        - repoURL: https://github.com/emov00/homelab-deployment.git
          targetRevision: main
          ref: values
      destination:
        name: homelab
        namespace: traefik
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
